language: python

cache: pip
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"

install:
  - pip install coveralls
  - pip install pytest
  - pip install pyflake8
  - pip install scipy
  - python setup.py -q install

script:
    - coverage run --source=acc pytest

after_script:
  - flake8 acc

after_success:
  - coveralls
