language: python

cache: pip
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      - python-scipy
      - python3-scipy
      - python-flake8

before_install:
    - pip install coveralls

script:
  - coverage run --source=acc python setup.py test

after_script:
  - flake8 .

after_success:
  - coveralls
